### ISSUE TITLE
On pf1_10_after example output

### ISSUE THREAD

**Issue by qu-tan-um** [onestruggler/quipper-qasm#1]
For `pf1_10_after`, the terminal keeps outputing 
`s1 in[0],in[1],in[2],in[3],in[4],in[5],in[6],in[7],in[8],in[9];`.

**Comment by onestruggler** [comment]
Inputs: 0:Qbit, 1:Qbit, 2:Qbit, 3:Qbit, 4:Qbit, 5:Qbit, 6:Qbit, 7:Qbit, 8:Qbit, 9:Qbit
Subroutine(x160000400)["S1", shape "([Q,Q,Q,Q,Q,Q,Q,Q,Q,Q],())"] (0,1,2,3,4,5,6,7,8,9) -> (0,1,2,3,4,5,6,7,8,9)
Outputs: 0:Qbit, 1:Qbit, 2:Qbit, 3:Qbit, 4:Qbit, 5:Qbit, 6:Qbit, 7:Qbit, 8:Qbit, 9:Qbit
-------------------------------------------------------------------------------------------------------------------
This is the first 3 lines in that file. The second line says, the subroutine repeats for 160000400 many times, and OpenQasm 2.0 doesn't support loops, so I have to repeat it, hence for the moment it is normal to keep outputing "s1 ....".
