### ISSUE TITLE
Generates invalid OpenQASM when initializing a qubit to the |1> state

### ISSUE THREAD

**Issue by fvoichick** [onestruggler/quipper-qasm#2]
I tried inputting the following Quipper output file:

    Inputs: none
    QInit1(0)
    Outputs: 0:Qbit

The result is the following OpenQASM file:

    OPENQASM 2.0;
    include "qelib1.inc";
    
    qreg in[0];
    
    qreg anc0[1];
    x anc[0];

This program refers to a register `anc` that has not been declared. Additionally, though I'm not sure if it's in the official language specification, IBM Quantum Composer disallows zero-length registers like `in`.

**Comment by onestruggler** [comment]
Thanks for pointing that out. I will look into it. I think the zero-length is just because I am too lazy to add a zero-length branch. For undeclared "anc", that is strange.

Fixed the bug in a not very good way. Please check it.

**Comment by fvoichick** [comment]
Your recent commit did not affect the source file **QasmPrinting.hs**, just a binary file **QasmPrinting**.

**Comment by onestruggler** [comment]
Sorry about that. I git added the wrongt file. Now it should be OK.

**Comment by fvoichick** [comment]
That seems to solve the issue, thanks!
